# Generated by Django 5.1.6 on 2025-03-09 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2025)])),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
