# Generated by Django 5.1.6 on 2025-03-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_lang',
            field=models.CharField(default='uz', max_length=30),
            preserve_default=False,
        ),
    ]
