# Generated by Django 5.1.6 on 2025-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(default='A-1', max_length=15),
            preserve_default=False,
        ),
    ]
