# Generated by Django 5.1.6 on 2025-04-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
