# Generated by Django 5.1.6 on 2025-03-09 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='group',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
