# Generated by Django 5.1.6 on 2025-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_lang'),
        ('pupils', '0002_pupil_course_alter_pupil_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='books.book'),
        ),
    ]
