# Generated by Django 5.1.6 on 2025-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_alter_pupil_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
