# Generated by Django 5.1.6 on 2025-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0005_alter_pupil_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='books',
        ),
        migrations.AlterField(
            model_name='pupil',
            name='group',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='pupil',
            name='books',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
