# Generated by Django 5.1.6 on 2025-04-21 17:26

import pupils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0006_remove_pupil_books_alter_pupil_group_pupil_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='face_image',
            field=models.ImageField(default='', upload_to=pupils.models.user_face_path),
            preserve_default=False,
        ),
    ]
